[package]
name = "emwin-parse"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
thiserror = "1.0"
chrono = "0.4"
nom = "7.1"
uom = { version = "0.33", default-features = false, features = ["f32", "si", "std"] }
bitflags = "1.3"
