[package]
name = "emwin-sql"
version = "0.1.0"
edition = "2021"

[dependencies]
emwin-parse = { path = "../emwin-parse" }
uom = { version = "0.33", default-features = false, features = ["f32", "si", "std"] }
sqlx = { version = "0.6", features = ["mysql"] }
log = { version = "0.4" }
